import Button from "./Button";

interface CardProps {
    title: string;
}

function Card ({ title } : CardProps) {
    return (
        <div className="card" style={styles.card}>
            <div className="card-content" style={styles.content}>
                <h1 style={styles.title}>{title}</h1>
            </div>
        </div>
    );
}

// move this to a style sheet later, inline is just quick and dirty. also I had this
// generated by coPilot so it may need some tweaking
const styles = {
    card: {
        border: '1px solid #ddd',
        borderRadius: '8px',
        overflow: 'hidden',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        maxWidth: '200px',
        margin: '16px',
    },
    content: {
        padding: '16px',
    },
    title: {
        fontSize: '1.5rem',
        margin: '0 0 8px',
    },
    description: {
        fontSize: '1rem',
        color: '#555',
    },
}

export default Card;