import Button from "./Button";
import Meal from "../models/mealSchema";
import "../../css/dashboard.css";


interface CardProps {
    title: string;
}

const Card: React.FC<CardProps> = ({ title }) => {
    // handler -> on click, creates meal. on clicking a meal, user can change / edit it
    function handleClick() {

    }

    // Card -> represents a "day" of meal plans
    return (
        <div className="card">
            <h1>{title}</h1>
            <div className="card-content">
                <Button onClick={handleClick} />
                <Button onClick={handleClick} />
                <Button onClick={handleClick} />
            </div>
        </div>
    );
};

// move this to a style sheet later, inline is just quick and dirty. also I had this
// generated by coPilot so it may need some tweaking
const styles = {
    card: {
        border: '1px solid #ddd',
        borderRadius: '8px',
        overflow: 'hidden',
        boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        maxWidth: '300px',
        minWidth: '200px',
        margin: '16px',
        height: '200px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    content: {
        padding: '16px',
    },
    title: {
        fontSize: '1.5rem',
        margin: '0 0 8px',
    },
    description: {
        fontSize: '1rem',
        color: '#555',
    },
};

export default Card;